### ISSUE TITLE
Fakeplayer

### ISSUE THREAD

**Issue by Marekone** [Darkhax-Minecraft/Game-Stages#48]
I should have mentioned before that I tried `ComputerCraft` as an alternative and it still didn't work.
I have the same problem with Buildcraft and I tried both spellings (`Buildcraft` and `[Buildcraft]`). The Quarry from Buildcraft can't destroy blocks either.

_Originally posted by @Marekone in https://github.com/Darkhax-Minecraft/Game-Stages/issues/47#issuecomment-574110390_

**Comment by Marekone** [comment]
I figured out how to get Buildcraft to work so only the problem with ComputerCraft is left.

It does not matter what i put in the fakeplayer config, turtles are not able to destroy blocks. I started the turtle from the lua console and got the error message: `Unbreakable block detected`. 
The turtle has no permission to destroy anything.

**Comment by Darkhax** [comment]
After dinging through the ComputerCraft code I don't see anything that would cause issues. Game Stages also doesn't cause blocks to become unbreakable so that sounds like it is an unrelated issue. If you are using some unspecified addon that does make blocks unbreakable then it could be an issue with that mod.
