### ISSUE TITLE
1.12.2 Data does not save

### ISSUE THREAD

**Issue by blacksythe** [Darkhax-Minecraft/Game-Stages#50]
On later versions of forge the saving of player gamestages appear to be broken.

[Link to original thread](https://github.com/Luohuayu/CatServer/issues/188)

**Comment by Darkhax** [comment]
Thank you for reporting this issue. Game Stages saves it's data when the player NBT file is saved or loaded. There was an ordering issue with the forge hooks where players log out before their data is saved. This ordering issue caused the player's data to be deleted before it could be properly saved. This is fixed in newer versions.

**Comment by wwkjfj** [comment]
Is this fixed in newer version of the mod, forge, or Minecraft?

**Comment by CleanCutBloons** [comment]
Newest version of the mod fixes it. Sorry for being late.
