### ISSUE TITLE
O(1) set.contains check for new strings are pretty slow

### ISSUE THREAD

**Issue by CaliforniaDemise** [Darkhax-Minecraft/Game-Stages#85]
## Environment Details
**Mod Version:** From oldest version to latest.
**Game Version:** From oldest game version to latest.
**Loader Type:** All
**Loader Version:** All
**Game Type:** All

## The Issue
In StageData class (or [PlayerData#L179](https://github.com/Darkhax-Minecraft/Game-Stages/blob/1.11.2/src/main/java/net/darkhax/gamestages/capabilities/PlayerDataHandler.java#L179) on 1.11.2 gamestages creates lowercase strings everytime any mod or crafttweaker checks for stages, this is a problem because string hash check is a slow progress.

Java caches the hash after hashCode is first called which significantly speeds up process when you do it again but it doesn't speed up in this case because toLowerCase creates a new string which gets discarded after stage is checked.

My suggestions are:
1. Handling toLowerCase when the stage is set instead of everytime it has been checked. This for example would speed up the JourneyMap Stages. You can remove toLowerCase entirely for newer game versions though.
2. Telling addon creators to add a reference to the stage string (like [here](https://github.com/Darkhax-Minecraft/JourneyMapStages/blob/master/src/main/java/net/darkhax/jmapstages/JMapStages.java#L26)) so they won't create new strings and make use of hash cache.
3. Limit the character amount of stage names to a power of two. Like for example 16 or 32 characters because strings use too many memory especially if they're not discarded.
4. Add localization support. This is kind of like a feature request but honestly it's an important one. You already use regex to limit stage names to ASCII which is a pretty good choice but there're people on overseas that would really like localization support. This would help people to use long stage names too.

## One Last Thing
I don't know but if you allow PR's for 1.12.2, I would like to post a PR to fix this issue in 1.12.2 too. Because people in 1.12.2 complains about it. I will release a fork if you entirely stopped supporting 1.12.2.

## Screenshots / Media
![image](https://github.com/user-attachments/assets/50bcf2a2-c095-4c4e-b5f5-9cc382386691)
![image](https://github.com/user-attachments/assets/9e7a30ae-f7ea-42d4-8539-552f1d1e5977)

**Comment by Darkhax** [comment]
Hello, it sounds like you may have some misconceptions. In Java `String#toLowerCase` will not create a new string if the input does not require any changes. Additionally, the JVM will generally intern newly created strings meaning they are not discarded and the cached state remains in tact. These calls do introduce a minuscule amount of CPU overhead but this has never been visible in profiling reports of benchmarks of GameStages. In the 1.21.x port we are switching from String to a new record type. This will allow us to validate the stage name upfront and make some of these behaviours more apparent in the code.

To address your suggests though

> Handling toLowerCase when the stage is set instead of everytime it has been checked. This for example would speed up the JourneyMap Stages. You can remove toLowerCase entirely for newer game versions though.

This is initially how GameStages worked, but several addons were allowing invalid stages to be created. These calls were added to ensure everything could continue to run smoothly and removing them now would be a breaking change. This will be addressed in the 1.21.x update as the new type will enforce validation.

> Telling addon creators to add a reference to the stage string (like [here](https://github.com/Darkhax-Minecraft/JourneyMapStages/blob/master/src/main/java/net/darkhax/jmapstages/JMapStages.java#L26)) so they won't create new strings and make use of hash cache.

Because strings are generally interned there is no benefit to doing this. They are already the same reference.

> Limit the character amount of stage names to a power of two. Like for example 16 or 32 characters because strings use too many memory especially if they're not discarded.

This would be an artificial limitation with no practical benefits. When strings are interned there is only one copy of them in memory and they are not easily discarded. If you want to avoid wasting a few bytes of extra ram just use shorter names. 

> Add localization support. This is kind of like a feature request but honestly it's an important one. You already use regex to limit stage names to ASCII which is a pretty good choice but there're people on overseas that would really like localization support. This would help people to use long stage names too.

Stage names are limited because they are internal IDs. They are not meant to be displayed to players under normal circumstances but many addons do allow you to customize how they are displayed and localized using the text component system. I can look into including a central API for this so the names are consistent across all addons but this would be a 1.21.x feature. 

> I don't know but if you allow PR's for 1.12.2, I would like to post a PR to fix this issue in 1.12.2 too. Because people in 1.12.2 complains about it. I will release a fork if you entirely stopped supporting 1.12.2.

Unfortunately I am not accepting new PRs for 1.12.2 at this time. A lot of the build tools for this version have crumbled so our CI/CD can not even build the project for these older versions. Feel free to make a fork if you feel it's still needed, just don't market it as official or send your users to my support channels. 

> ![](https://private-user-images.githubusercontent.com/155631180/363410000-9e7a30ae-f7ea-42d4-8539-552f1d1e5977.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjAxMDQsIm5iZiI6MTcyNTI1OTgwNCwicGF0aCI6Ii8xNTU2MzExODAvMzYzNDEwMDAwLTllN2EzMGFlLWY3ZWEtNDJkNC04NTM5LTU1MmYxZDFlNTk3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwNjUwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzA1OTQzZTkzZGMxZTE1OTllMmFmZjhiY2UyNzMxNzhmMDUxYmM5OTEzYzVmNzVjZWJiZjM5ZjE0MGUwNzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gq2f2RbWARlpiq1Zlph27Yi30O9fimgDC4y7bI0GmQI)

It's not clear what they're talking about, but Game Stages does have a reputation for hurting game performance. This reputation primarily comes from addons and poorly optimized packs. For example packs using ItemStages to create thousands of new restrictions for the same stage rather than one restriction that checks if the item is in a tag. There is definitely room to optimize and improve the mod and its addons but it's worth noting that there are some very large projects that do things correctly and do not have these issues as a result.

**Comment by CaliforniaDemise** [comment]
Ah didn't look that deep into lowercase and uppercase, thanks for clarification. Good choice to use records too. People do use uppercase letters though, like ROTN, I guess newer versions does the regex check though so it only occurs in 1.12.2. I just thought this was another potential performance problem other than the addons like ItemStages.

Central API for localization would really help people because 3rd-party developers sometimes forget about details like that.

Other than that, It would be great if you can redirect 1.12.2 users to my fork.
